/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#93ccff',
        'on-secondary-fixed': '#001e2f',
        'on-primary-container': '#fdfcff',
        'surface-dim': '#d2d9f4',
        'surface-container': '#eaedff',
        'surface-variant': '#dae2fd',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-primary-fixed': '#001d31',
        'on-tertiary-container': '#fcfcff',
        'on-tertiary-fixed': '#001e2c',
        'tertiary-fixed': '#c4e7ff',
        'on-surface': '#131b2e',
        'primary-container': '#007bb9',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#3f4850',
        'secondary': '#006591',
        'primary-fixed': '#cce5ff',
        'surface-container-highest': '#dae2fd',
        'outline-variant': '#bfc7d2',
        'surface': '#faf8ff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#004c69',
        'secondary-container': '#39b8fd',
        'outline': '#707881',
        'secondary-fixed': '#c9e6ff',
        'surface-container-low': '#f2f3ff',
        'background': '#faf8ff',
        'on-secondary': '#ffffff',
        'inverse-surface': '#283044',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'error': '#ba1a1a',
        'primary': '#006194',
        'on-background': '#131b2e',
        'primary-fixed-dim': '#93ccff',
        'surface-tint': '#006398',
        'secondary-fixed-dim': '#89ceff',
        'surface-container-high': '#e2e7ff',
        'on-primary-fixed-variant': '#004b73',
        'tertiary': '#006387',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eef0ff',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#004c6e',
        'on-secondary-container': '#004666',
        'tertiary-container': '#007da9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4.5rem',
        'space-4xl': '6rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'margin-mobile': '1rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
      },
      fontFamily: {
        'display-hero': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'code-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'code-mono': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
